### ISSUE TITLE
Build fails with ERROR: LoadError: UndefVarError: C_FILE not defined

### ISSUE THREAD

**Issue by mauro3** [JuliaComputing/static-julia#16]
This line https://github.com/JuliaComputing/static-julia/blob/0717797999f2cf0cae059704a38dd9951597a6b9/juliac.jl#L33 is where the issue is.  I think it should read:

```
command = `gcc -m64 program.c -o $filename $SO_FILE $cflags $ldflags $ldlibs -Wl,-rpath,\$ORIGIN`
```

**Comment by lucatrv** [comment]
This is fixed by my next PR, currently in review
