### ISSUE TITLE
how can I custom the “image_file“

### ISSUE THREAD

**Issue by moldray** [JuliaComputing/static-julia#22]
the build is successed, but when I run my program,  I got the error `ERROR: could not load library "mypath/builddir/libhello"`

I found that the image_file is hard coded in `program.c` in line 21:

` jl_options.image_file = "libhello";`

so, how can I custom it?

**Comment by lucatrv** [comment]
With Julia 0.7 this will no more be an issue, see last paragraph of 'README.md'

**Comment by moldray** [comment]
@lucatrv thanks
