### ISSUE TITLE
How to get ARGS from CLI

### ISSUE THREAD

**Issue by moldray** [JuliaComputing/static-julia#23]
After compiled, How can I get `ARGS` from command line? For example, when I run `./hello abc`, How to get `abc` in my code？ I can use `ARGS` in script, but when the code is compiled to binary, it is not work.

**Comment by chengchingwen** [comment]
I have a similar problem, if I use ```ARGS``` in script, the binary crash with a segmentation fault.

**Comment by chengchingwen** [comment]
Look at ```program2.c```, you need to wrap ```argv``` into julia object and passed it to ```julia_main```

**Comment by moldray** [comment]
@chengchingwen Dose it means that the ARGS can only be passed in julia 0.7 ？

**Comment by chengchingwen** [comment]
@moldray I test with julia v0.6. It works fine.

**Comment by moldray** [comment]
@chengchingwen thks
