### ISSUE TITLE
Building so versions of packages?

### ISSUE THREAD

**Issue by timholy** [JuliaComputing/static-julia#31]
This looks helpful, I've long meant to play with AOT compilation but have never gotten around to figuring out what it can do.

Question: is it feasible to use this to create a shared lib that eliminates precompilation overhead? E.g., an `Images.so` file that contains a precompiled (to machine code) library? But one that can be used in interactive (REPL) sessions?

**Comment by ViralBShah** [comment]
Not at the moment. You have to build everything into the system image.

A bunch of compiler work is necessary to support multiple libraries - like `Images.so`. We probably also need to work to ensure that all the common relevant methods are compiled to machine code as part of that (like SnoopCompile). @vtjnash says there is a bunch of work to be done before we can have native precompiled packages.

That is certainly the direction though post 1.0.

**Comment by timholy** [comment]
Thanks. I don't think having this issue open accomplishes anything (sounds like it's already on everyone's radar), so I'll close this.
