### ISSUE TITLE
Readme example fails when renaming hello.jl to hi.jl

### ISSUE THREAD

**Issue by vvjn** [JuliaComputing/static-julia#47]
When I rename hello.jl to hl.jl and run `julia juliac.jl -ve hi.jl` it fails. The resulting binary tried to look for libhello.so. I came across this when compiling my own code failed (same error message), but when I renamed it to hello.jl, it worked.

This was on Ubuntu 16.04 (4.10.0-38-generic #42~16.04.1-Ubuntu SMP x86_64) and Julia 0.6.1. The following is the error message I got.

```
vvjn@rocket:~/static-julia-master$ mv hello.jl hi.jl
vvjn@rocket:~/static-julia-master$ julia juliac.jl -ve hi.jl
Julia program file:
"/home/vvjn/static-julia-master/hi.jl"
C program file:
"/home/vvjn/static-julia-master/program.c"
Build directory:
"/home/vvjn/static-julia-master/builddir"
Change to build directory
Build object file "hi.o":
`/home/vvjn/opt/julia/bin/julia -Cx86-64 -J/home/vvjn/opt/julia/lib/julia/sys.so --compile=yes --depwarn=yes --startup-file=no --output-o hi.o -e 'include("/home/vvjn/static-julia-master/hi.jl"); push!(Base.LOAD_CACHE_PATH, "/home/vvjn/.julia/lib/v0.6"); empty!(Base.LOAD_CACHE_PATH)'`

Build shared library "libhi.so":
`gcc -m64 -shared -o libhi.so hi.o -std=gnu99 -I/home/vvjn/opt/julia/include/julia -DJULIA_ENABLE_THREADING=1 -fPIC -L/home/vvjn/opt/julia/lib -Wl,--export-dynamic -Wl,-rpath,/home/vvjn/opt/julia/lib -Wl,-rpath,/home/vvjn/opt/julia/lib/julia -ljulia`
Build executable file "hi":
`gcc -m64 -o hi /home/vvjn/static-julia-master/program.c libhi.so -std=gnu99 -I/home/vvjn/opt/julia/include/julia -DJULIA_ENABLE_THREADING=1 -fPIC -L/home/vvjn/opt/julia/lib -Wl,--export-dynamic -Wl,-rpath,/home/vvjn/opt/julia/lib -Wl,-rpath,/home/vvjn/opt/julia/lib/julia -ljulia '-Wl,-rpath,$ORIGIN'`
Delete object file "hi.o"
vvjn@rocket:~/static-julia-master$
vvjn@rocket:~/static-julia-master$ cd builddir/
vvjn@rocket:~/static-julia-master/builddir$ ls
hi  libhi.so
vvjn@rocket:~/static-julia-master/builddir$ ./hi
ERROR: could not load library "/home/vvjn/static-julia-master/builddir/libhello"
/home/vvjn/static-julia-master/builddir/libhello.so: cannot open shared object file: No such file or directory
```

**Comment by phlavenk** [comment]
Hi,
for the compilation into executable, two source files are needes - the hello.jl and program.c. During compilation, hello.jl compiles into hello.so and program.c compiles into small executable, that dynamically loads the large hello.so library. As stated in Readme.md, the name of the shared library (here hello.so) is hard-coded in the program.c file:  `For now, the image file has to be changed in program.c to match the name of the shared library containing the compiled julia program.`
So you have to change also the library name in the program.c if you want to rename it.

**Comment by vvjn** [comment]
Thanks, that works very well. Really should've read all of the readme file first. I'm closing this.

**Comment by lucatrv** [comment]
PR #55 fixes this, now you do not need to modify `program.c` anymore.
