### ISSUE TITLE
undefined reference to `julia_main'

### ISSUE THREAD

**Issue by comboy99** [JuliaComputing/static-julia#9]
Hi, I encountered an error and tried to find a solution but, I could not find it until now.

I will be happy if you give me some advice.

> julia juliac.jl hello.jl "C:\Users\Donghyeon Kim\AppData\Local\Julia-0.6.0" "C:\Users\Donghyeon Kim\AppData\Local\Julia-0.6.0"
Program File : hello.jl
Julia Install Path: C:\Users\Donghyeon Kim\AppData\Local\Julia-0.6.0
C:\Users\DONGHY~1\AppData\Local\Temp\ccDaHl7Q.o:program.c:(.text+0x4d): undefined reference to `julia_main'
collect2.exe: error: ld returned 1 exit status
ERROR: LoadError: failed process: Process(`x86_64-w64-mingw32-gcc -m64 program.c -o hello.exe libhello.dll -std=gnu99 '-IC:\Users\Donghyeon Kim\AppData\Local\Julia-0.6.0\include\julia' -DJULIA_ENABLE_THREADING=1 '-LC:\Users\Donghyeon Kim\AppData\Local\Julia-0.6.0\bin' -Wl,--stack,8388608 -ljulia -lopenlibm -lopenlibm '-Wl,-rpath,$ORIGIN'`, ProcessExited(1)) [1]
Stacktrace:
 [1] pipeline_error(::Base.Process) at .\process.jl:682
 [2] run(::Cmd) at .\process.jl:651
 [3] compile(::String, ::String, ::String) at D:\workspace\Git\Julia_MshSimEngine\static-julia\juliac.jl:32
 [4] include_from_node1(::String) at .\loading.jl:569
 [5] include(::String) at .\sysimg.jl:14
 [6] process_options(::Base.JLOptions) at .\client.jl:305
 [7] _start() at .\client.jl:371
while loading D:\workspace\Git\Julia_MshSimEngine\static-julia\juliac.jl, in expression starting on line 51

**Comment by fguevaravas** [comment]
I had the same problem. What worked for me was modifying [julia.jl, line 31](https://github.com/JuliaComputing/static-julia/blob/24b99ef4c13f5ebcfc180c76e107ea6cc6ebca1d/juliac.jl#L31) to add the option `-Wl,-export-all-symbols`, that is:
```julia
run(`x86_64-w64-mingw32-gcc -m64 -fPIC -Wl,-export-all-symbols -shared -o $(SO_FILE) $(O_FILE) $(ldflags) $(ldlibs)`)
```
